// Editor state = exactly the script.json content. Every action produces the
// next valid script.json — malformed scripts are impossible by construction.
//
// Invariants (project spec §5.1):
//  - line and character ids are UUIDs, minted once and NEVER reused;
//  - ids are UNIQUE and match SAFE_ID (they become clip filenames — the
//    GitHub Action enforces the same pattern, see scripts/process_uploads.py);
//  - moving/editing a line keeps its id; only ADD_LINE mints a new id;
//  - a line references its character by characterId, never by name.
//
// UUIDs are generated by the EVENT HANDLERS (newId()) and carried in the
// action, never inside the reducer: reducers must stay pure (React may
// replay them). Exception: sanitizeScript may remint ids, but it only runs
// on LOAD_SCRIPT to repair hand-edited files.

export function newId() {
  return crypto.randomUUID();
}

// Mirror of LINE_ID_PATTERN in scripts/process_uploads.py — keep in sync.
export const SAFE_ID = /^[0-9a-zA-Z-]{1,64}$/;

export const EMPTY_SCRIPT = {
  title: "",
  characters: [],
  acts: [{ title: "Acte I", scenes: [{ title: "Scène 1", lines: [] }] }],
};

const isId = (value) => typeof value === "string" && SAFE_ID.test(value);

// Defensive normalization of a loaded script.json (the published file can be
// hand-edited on github.com): fills missing fields, drops malformed entries,
// and heals invalid or DUPLICATED ids by minting fresh UUIDs — duplicate ids
// would corrupt React keys, dnd-kit sorting and status computation.
export function sanitizeScript(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) raw = {};

  const seenIds = new Set();
  // Character ids that had to be reminted map old -> new so their lines
  // follow them.
  const characterRemap = new Map();

  const characters = (Array.isArray(raw.characters) ? raw.characters : [])
    .filter((c) => c && typeof c === "object" && typeof c.name === "string" && c.name.trim())
    .map((c) => {
      let id = c.id;
      if (!isId(id) || seenIds.has(id)) {
        const fresh = newId();
        if (isId(id)) characterRemap.set(id, fresh); // duplicate: keep first owner
        id = fresh;
      }
      seenIds.add(id);
      return { id, name: c.name };
    });
  const characterIds = new Set(characters.map((c) => c.id));

  const sanitizeLine = (l) => {
    if (!l || typeof l !== "object") return null;
    let id = l.id;
    if (!isId(id) || seenIds.has(id)) id = newId();
    seenIds.add(id);
    let characterId = isId(l.characterId) ? l.characterId : null;
    if (characterId && characterRemap.has(characterId)) characterId = characterRemap.get(characterId);
    if (characterId && !characterIds.has(characterId)) characterId = null;
    return { id, characterId, text: typeof l.text === "string" ? l.text : "" };
  };

  return {
    title: typeof raw.title === "string" ? raw.title : "",
    characters,
    acts:
      Array.isArray(raw.acts) && raw.acts.length > 0
        ? raw.acts
            .filter((act) => act && typeof act === "object")
            .map((act, ai) => ({
              title: typeof act.title === "string" ? act.title : `Acte ${ai + 1}`,
              scenes:
                Array.isArray(act.scenes) && act.scenes.length > 0
                  ? act.scenes
                      .filter((scene) => scene && typeof scene === "object")
                      .map((scene, si) => ({
                        title: typeof scene.title === "string" ? scene.title : `Scène ${si + 1}`,
                        lines: Array.isArray(scene.lines)
                          ? scene.lines.map(sanitizeLine).filter(Boolean)
                          : [],
                      }))
                  : [{ title: "Scène 1", lines: [] }],
            }))
        : EMPTY_SCRIPT.acts,
  };
}

export function allLines(script) {
  return script.acts.flatMap((a) => a.scenes.flatMap((s) => s.lines));
}

export function countLinesOfCharacter(script, characterId) {
  return allLines(script).filter((l) => l.characterId === characterId).length;
}

// Default character for a line inserted after index `idx` in `scene`:
// ALTERNATION — a dialogue between A and B can be typed with Enter only.
// Insert after a line of B whose previous line is from A -> default A.
// Fallbacks: the previous line's character, then the first character.
function defaultCharacterId(scene, idx, characters) {
  const prev = scene.lines[idx];
  const beforePrev = scene.lines[idx - 1];
  if (
    prev?.characterId != null &&
    beforePrev?.characterId != null &&
    beforePrev.characterId !== prev.characterId
  ) {
    return beforePrev.characterId;
  }
  if (prev?.characterId != null) return prev.characterId;
  return characters[0]?.id ?? null;
}

// Immutably update one scene designated by indices. Only that scene's
// object changes identity — untouched acts/scenes keep theirs, which is what
// lets React.memo skip re-rendering the rest of the play on every keystroke.
function updateScene(state, actIndex, sceneIndex, fn) {
  return {
    ...state,
    acts: state.acts.map((act, ai) =>
      ai !== actIndex
        ? act
        : {
            ...act,
            scenes: act.scenes.map((scene, si) => (si !== sceneIndex ? scene : fn(scene))),
          }
    ),
  };
}

// Immutably update every line of the script (rare, character-level ops only).
function mapAllLines(state, fn) {
  return {
    ...state,
    acts: state.acts.map((act) => ({
      ...act,
      scenes: act.scenes.map((scene) => ({
        ...scene,
        lines: scene.lines.map(fn).filter(Boolean),
      })),
    })),
  };
}

export function scriptReducer(state, action) {
  switch (action.type) {
    case "LOAD_SCRIPT":
      return sanitizeScript(action.script);

    case "SET_TITLE":
      return { ...state, title: action.title };

    // ---- Characters (side panel referential) ----

    case "ADD_CHARACTER": {
      // action.id: UUID minted by the caller.
      const name = action.name.trim();
      if (!name) return state;
      return {
        ...state,
        characters: [...state.characters, { id: action.id, name }],
      };
    }

    case "RENAME_CHARACTER": {
      const name = action.name.trim();
      if (!name) return state;
      // Renaming only touches the referential — no line id changes, so no
      // recording ever becomes stale because of a rename.
      return {
        ...state,
        characters: state.characters.map((c) => (c.id === action.id ? { ...c, name } : c)),
      };
    }

    case "DELETE_CHARACTER": {
      // action.mode: "reassign" (to action.reassignTo) or "deleteLines".
      // Characters with no lines can be deleted with either mode.
      let next = state;
      if (action.mode === "reassign" && action.reassignTo != null) {
        next = mapAllLines(next, (l) =>
          l.characterId === action.id ? { ...l, characterId: action.reassignTo } : l
        );
      } else {
        next = mapAllLines(next, (l) => (l.characterId === action.id ? null : l));
      }
      return {
        ...next,
        characters: next.characters.filter((c) => c.id !== action.id),
      };
    }

    // ---- Acts & scenes ----

    case "ADD_ACT":
      return {
        ...state,
        acts: [
          ...state.acts,
          { title: `Acte ${state.acts.length + 1}`, scenes: [{ title: "Scène 1", lines: [] }] },
        ],
      };

    case "RENAME_ACT":
      return {
        ...state,
        acts: state.acts.map((a, i) => (i === action.actIndex ? { ...a, title: action.title } : a)),
      };

    case "DELETE_ACT":
      return { ...state, acts: state.acts.filter((_, i) => i !== action.actIndex) };

    case "ADD_SCENE":
      return {
        ...state,
        acts: state.acts.map((a, i) =>
          i !== action.actIndex
            ? a
            : { ...a, scenes: [...a.scenes, { title: `Scène ${a.scenes.length + 1}`, lines: [] }] }
        ),
      };

    case "RENAME_SCENE":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        title: action.title,
      }));

    case "DELETE_SCENE":
      return {
        ...state,
        acts: state.acts.map((a, i) =>
          i !== action.actIndex ? a : { ...a, scenes: a.scenes.filter((_, si) => si !== action.sceneIndex) }
        ),
      };

    // ---- Lines (all scoped to one scene: O(scene), not O(whole play)) ----

    case "ADD_LINE": {
      // Insert after line `afterLineId` (or append when null).
      // action.id: UUID minted by the caller (which also uses it to focus
      // the new line's textarea). The default character (alternation) is
      // computed here — pure, from state + action only.
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const idx =
          action.afterLineId == null
            ? scene.lines.length - 1
            : scene.lines.findIndex((l) => l.id === action.afterLineId);
        const newLine = {
          id: action.id,
          characterId: defaultCharacterId(scene, idx, state.characters),
          text: "",
        };
        const lines = [...scene.lines];
        lines.splice(idx + 1, 0, newLine);
        return { ...scene, lines };
      });
    }

    case "EDIT_TEXT":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.map((l) => (l.id === action.lineId ? { ...l, text: action.text } : l)),
      }));

    case "SET_LINE_CHARACTER":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.map((l) =>
          l.id === action.lineId ? { ...l, characterId: action.characterId } : l
        ),
      }));

    case "DELETE_LINE":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.filter((l) => l.id !== action.lineId),
      }));

    case "MOVE_LINE": {
      // Reorder within a scene: the moved line keeps its id (ids travel with
      // the object).
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const from = scene.lines.findIndex((l) => l.id === action.activeId);
        const to = scene.lines.findIndex((l) => l.id === action.overId);
        if (from === -1 || to === -1 || from === to) return scene;
        const lines = [...scene.lines];
        const [moved] = lines.splice(from, 1);
        lines.splice(to, 0, moved);
        return { ...scene, lines };
      });
    }

    default:
      return state;
  }
}
